language: python
python:
  - 3.6
  - 3.7
install:
  - pip install -r requirements/base.txt
  - pip install -r requirements/devel.txt
  - pip install -r requirements/tests.txt
script:
  - pytest
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  on:
    tags: true
  user: "__token__"
  password:
    secure: upF9ChYklNX9P1WQmydWjfVF8MZyYTj7WRiF9UeG/JLLgWE18MzeLmhibzvLy8qE1d1PBjdBY45m8PKnNGfvT5UCDFyVcYoodiLpHZ9MgXCYCCoKDLJBm0SA0CkmbJ3M29zLIGzIEJrwDhFihQBdHYMIh4tRbMi/QwfeHoy/R7KXyeBxyhAe1tZAns6u6i9fgP9ECwK112cznNCf759Rapu6CAzV9wpzM/FYTzttcyiPuAoD7AflfRZS4s+MUqQXC3EHqrV6girzai7yiWSfUP3+XFME7wZVPgDORo9MBvG67UpIIy+seZ4Y11p+gr6qJmVWjRSePwW5zevOTJXXGyaLuUkFHp1xrAXC16pufqau8NFQYo5e8P771c3T3Fn+uQvQ9onyYW2lSXhHJOqrVA07jni8HuYKuh8PgCxld4zdQYrUpW32PxQBdV9pyuBapAJmmad0Pj8MSkPI8+9ffma/P1Cz9RXPJxTqV0WqWaNy+mODZ1NIQPW2LHqImoTGML/k97pmRth77BGNDGnNqcs9x1UL7TCXTif/BKhm4Cfb3O5HZDJBsyetMDHdUHwMYrqYFKiSf4i841RGk5fruVksdJwu3EWCPy18MY7rV7HwbEtsV9FiZ8b2f5Osk8rjZ9VDYu8rDe2iz9tZfKxJM3HjcqB+RLmULXCEYWRFn3Y=
